### ISSUE TITLE
Padres

### ISSUE THREAD

**Issue by JIPieroni** [pdepmartestm/bienvenida-2023-CelesteDellisola#2]
Felicitaciones por representarnos Celeste genia ; una sugerencia podrías  agregar una foto de tus padres o tuya en tu nuevo hobby con el kickboxing saludoss.

**Comment by CelesteDellisola** [comment]
Muchas gracias!! Y siii! Dale! … es más! Ahora en un rato subo una foto con mi papá y hermano que participamos juntos en el Centro Sudamericano de Brasil❤️❤️❤️

**Comment by CelesteDellisola** [comment]
Perfecto! Ya pude subir la foto y comente una pequeña descripcion abajo para que lo puedan leer y entender! Gracias por comentar en mi README...Saludos!
